/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.imshello.baseWRAP;

public class AudioResampler {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AudioResampler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AudioResampler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        baseWRAPJNI.delete_AudioResampler(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AudioResampler(long nInFreq, long nOutFreq, long nFrameDuration, long nChannels, long nQuality) {
    this(baseWRAPJNI.new_AudioResampler(nInFreq, nOutFreq, nFrameDuration, nChannels, nQuality), true);
  }

  public boolean isValid() {
    return baseWRAPJNI.AudioResampler_isValid(swigCPtr, this);
  }

  public long getOutputRequiredSizeInShort() {
    return baseWRAPJNI.AudioResampler_getOutputRequiredSizeInShort(swigCPtr, this);
  }

  public long getInputRequiredSizeInShort() {
    return baseWRAPJNI.AudioResampler_getInputRequiredSizeInShort(swigCPtr, this);
  }

  public long process(java.nio.ByteBuffer pInData, long nInSizeInBytes, java.nio.ByteBuffer pOutData, long nOutSizeInBytes) {
    return baseWRAPJNI.AudioResampler_process(swigCPtr, this, pInData, nInSizeInBytes, pOutData, nOutSizeInBytes);
  }

}
