/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.imshello.baseWRAP;

public class Codec {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Codec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Codec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        baseWRAPJNI.delete_Codec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public twrap_media_type_t getMediaType() {
    return twrap_media_type_t.swigToEnum(baseWRAPJNI.Codec_getMediaType(swigCPtr, this));
  }

  public String getName() {
    return baseWRAPJNI.Codec_getName(swigCPtr, this);
  }

  public String getDescription() {
    return baseWRAPJNI.Codec_getDescription(swigCPtr, this);
  }

  public String getNegFormat() {
    return baseWRAPJNI.Codec_getNegFormat(swigCPtr, this);
  }

  public int getAudioSamplingRate() {
    return baseWRAPJNI.Codec_getAudioSamplingRate(swigCPtr, this);
  }

  public int getAudioChannels() {
    return baseWRAPJNI.Codec_getAudioChannels(swigCPtr, this);
  }

  public int getAudioPTime() {
    return baseWRAPJNI.Codec_getAudioPTime(swigCPtr, this);
  }

}
