/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.imshello.baseWRAP;

public class InfoEvent extends SipEvent {
  private long swigCPtr;

  protected InfoEvent(long cPtr, boolean cMemoryOwn) {
    super(baseWRAPJNI.InfoEvent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InfoEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        baseWRAPJNI.delete_InfoEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public tsip_info_event_type_t getType() {
    return tsip_info_event_type_t.swigToEnum(baseWRAPJNI.InfoEvent_getType(swigCPtr, this));
  }

  public InfoSession getSession() {
    long cPtr = baseWRAPJNI.InfoEvent_getSession(swigCPtr, this);
    return (cPtr == 0) ? null : new InfoSession(cPtr, false);
  }

  public InfoSession takeSessionOwnership() {
    long cPtr = baseWRAPJNI.InfoEvent_takeSessionOwnership(swigCPtr, this);
    return (cPtr == 0) ? null : new InfoSession(cPtr, false);
  }

}
