/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.imshello.baseWRAP;

public class InviteSession extends SipSession {
  private long swigCPtr;

  protected InviteSession(long cPtr, boolean cMemoryOwn) {
    super(baseWRAPJNI.InviteSession_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InviteSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        baseWRAPJNI.delete_InviteSession(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public InviteSession(SipStack Stack) {
    this(baseWRAPJNI.new_InviteSession(SipStack.getCPtr(Stack), Stack), true);
  }

  public boolean accept(ActionConfig config) {
    return baseWRAPJNI.InviteSession_accept__SWIG_0(swigCPtr, this, ActionConfig.getCPtr(config), config);
  }

  public boolean accept() {
    return baseWRAPJNI.InviteSession_accept__SWIG_1(swigCPtr, this);
  }

  public boolean hangup(ActionConfig config) {
    return baseWRAPJNI.InviteSession_hangup__SWIG_0(swigCPtr, this, ActionConfig.getCPtr(config), config);
  }

  public boolean hangup() {
    return baseWRAPJNI.InviteSession_hangup__SWIG_1(swigCPtr, this);
  }

  public boolean reject(ActionConfig config) {
    return baseWRAPJNI.InviteSession_reject__SWIG_0(swigCPtr, this, ActionConfig.getCPtr(config), config);
  }

  public boolean reject() {
    return baseWRAPJNI.InviteSession_reject__SWIG_1(swigCPtr, this);
  }

  public boolean sendInfo(java.nio.ByteBuffer payload, long len, ActionConfig config) {
    return baseWRAPJNI.InviteSession_sendInfo__SWIG_0(swigCPtr, this, payload, len, ActionConfig.getCPtr(config), config);
  }

  public boolean sendInfo(java.nio.ByteBuffer payload, long len) {
    return baseWRAPJNI.InviteSession_sendInfo__SWIG_1(swigCPtr, this, payload, len);
  }

  public MediaSessionMgr getMediaMgr() {
    long cPtr = baseWRAPJNI.InviteSession_getMediaMgr(swigCPtr, this);
    return (cPtr == 0) ? null : new MediaSessionMgr(cPtr, false);
  }

}
