/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.imshello.baseWRAP;

public class MsrpMessage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MsrpMessage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MsrpMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        baseWRAPJNI.delete_MsrpMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MsrpMessage() {
    this(baseWRAPJNI.new_MsrpMessage(), true);
  }

  public boolean isRequest() {
    return baseWRAPJNI.MsrpMessage_isRequest(swigCPtr, this);
  }

  public short getCode() {
    return baseWRAPJNI.MsrpMessage_getCode(swigCPtr, this);
  }

  public String getPhrase() {
    return baseWRAPJNI.MsrpMessage_getPhrase(swigCPtr, this);
  }

  public tmsrp_request_type_t getRequestType() {
    return tmsrp_request_type_t.swigToEnum(baseWRAPJNI.MsrpMessage_getRequestType(swigCPtr, this));
  }

  public void getByteRange(long[] arg0, long[] arg1, long[] arg2) {
    baseWRAPJNI.MsrpMessage_getByteRange(swigCPtr, this, arg0, arg1, arg2);
  }

  public boolean isLastChunck() {
    return baseWRAPJNI.MsrpMessage_isLastChunck(swigCPtr, this);
  }

  public boolean isFirstChunck() {
    return baseWRAPJNI.MsrpMessage_isFirstChunck(swigCPtr, this);
  }

  public boolean isSuccessReport() {
    return baseWRAPJNI.MsrpMessage_isSuccessReport(swigCPtr, this);
  }

  public String getMsrpHeaderValue(String name) {
    return baseWRAPJNI.MsrpMessage_getMsrpHeaderValue(swigCPtr, this, name);
  }

  public String getMsrpHeaderParamValue(String name, String param) {
    return baseWRAPJNI.MsrpMessage_getMsrpHeaderParamValue(swigCPtr, this, name, param);
  }

  public long getMsrpContentLength() {
    return baseWRAPJNI.MsrpMessage_getMsrpContentLength(swigCPtr, this);
  }

  public long getMsrpContent(java.nio.ByteBuffer output, long maxsize) {
    return baseWRAPJNI.MsrpMessage_getMsrpContent(swigCPtr, this, output, maxsize);
  }

}
