/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.imshello.baseWRAP;

public class OptionsSession extends SipSession {
  private long swigCPtr;

  protected OptionsSession(long cPtr, boolean cMemoryOwn) {
    super(baseWRAPJNI.OptionsSession_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptionsSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        baseWRAPJNI.delete_OptionsSession(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptionsSession(SipStack pStack) {
    this(baseWRAPJNI.new_OptionsSession(SipStack.getCPtr(pStack), pStack), true);
  }

  public boolean send(ActionConfig config) {
    return baseWRAPJNI.OptionsSession_send__SWIG_0(swigCPtr, this, ActionConfig.getCPtr(config), config);
  }

  public boolean send() {
    return baseWRAPJNI.OptionsSession_send__SWIG_1(swigCPtr, this);
  }

  public boolean accept(ActionConfig config) {
    return baseWRAPJNI.OptionsSession_accept__SWIG_0(swigCPtr, this, ActionConfig.getCPtr(config), config);
  }

  public boolean accept() {
    return baseWRAPJNI.OptionsSession_accept__SWIG_1(swigCPtr, this);
  }

  public boolean reject(ActionConfig config) {
    return baseWRAPJNI.OptionsSession_reject__SWIG_0(swigCPtr, this, ActionConfig.getCPtr(config), config);
  }

  public boolean reject() {
    return baseWRAPJNI.OptionsSession_reject__SWIG_1(swigCPtr, this);
  }

}
