/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.imshello.baseWRAP;

public class ProxyVideoProducerCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ProxyVideoProducerCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProxyVideoProducerCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        baseWRAPJNI.delete_ProxyVideoProducerCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    baseWRAPJNI.ProxyVideoProducerCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    baseWRAPJNI.ProxyVideoProducerCallback_change_ownership(this, swigCPtr, true);
  }

  public ProxyVideoProducerCallback() {
    this(baseWRAPJNI.new_ProxyVideoProducerCallback(), true);
    baseWRAPJNI.ProxyVideoProducerCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public int prepare(int width, int height, int fps) {
    return (getClass() == ProxyVideoProducerCallback.class) ? baseWRAPJNI.ProxyVideoProducerCallback_prepare(swigCPtr, this, width, height, fps) : baseWRAPJNI.ProxyVideoProducerCallback_prepareSwigExplicitProxyVideoProducerCallback(swigCPtr, this, width, height, fps);
  }

  public int start() {
    return (getClass() == ProxyVideoProducerCallback.class) ? baseWRAPJNI.ProxyVideoProducerCallback_start(swigCPtr, this) : baseWRAPJNI.ProxyVideoProducerCallback_startSwigExplicitProxyVideoProducerCallback(swigCPtr, this);
  }

  public int pause() {
    return (getClass() == ProxyVideoProducerCallback.class) ? baseWRAPJNI.ProxyVideoProducerCallback_pause(swigCPtr, this) : baseWRAPJNI.ProxyVideoProducerCallback_pauseSwigExplicitProxyVideoProducerCallback(swigCPtr, this);
  }

  public int stop() {
    return (getClass() == ProxyVideoProducerCallback.class) ? baseWRAPJNI.ProxyVideoProducerCallback_stop(swigCPtr, this) : baseWRAPJNI.ProxyVideoProducerCallback_stopSwigExplicitProxyVideoProducerCallback(swigCPtr, this);
  }

}
