/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.imshello.baseWRAP;

public class ProxyVideoProducer extends ProxyPlugin {
  private long swigCPtr;

  protected ProxyVideoProducer(long cPtr, boolean cMemoryOwn) {
    super(baseWRAPJNI.ProxyVideoProducer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProxyVideoProducer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        baseWRAPJNI.delete_ProxyVideoProducer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int getRotation() {
    return baseWRAPJNI.ProxyVideoProducer_getRotation(swigCPtr, this);
  }

  public boolean setRotation(int nRot) {
    return baseWRAPJNI.ProxyVideoProducer_setRotation(swigCPtr, this, nRot);
  }

  public boolean setActualCameraOutputSize(long nWidth, long nHeight) {
    return baseWRAPJNI.ProxyVideoProducer_setActualCameraOutputSize(swigCPtr, this, nWidth, nHeight);
  }

  public int push(java.nio.ByteBuffer pBuffer, long nSize) {
    return baseWRAPJNI.ProxyVideoProducer_push(swigCPtr, this, pBuffer, nSize);
  }

  public void setCallback(ProxyVideoProducerCallback pCallback) {
    baseWRAPJNI.ProxyVideoProducer_setCallback(swigCPtr, this, ProxyVideoProducerCallback.getCPtr(pCallback), pCallback);
  }

  public java.math.BigInteger getMediaSessionId() {
    return baseWRAPJNI.ProxyVideoProducer_getMediaSessionId(swigCPtr, this);
  }

  public static boolean registerPlugin() {
    return baseWRAPJNI.ProxyVideoProducer_registerPlugin();
  }

  public static void setDefaultChroma(tmedia_chroma_t eChroma) {
    baseWRAPJNI.ProxyVideoProducer_setDefaultChroma(eChroma.swigValue());
  }

}
