/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.imshello.baseWRAP;

public class ProxyAudioProducer extends ProxyPlugin {
  private long swigCPtr;

  protected ProxyAudioProducer(long cPtr, boolean cMemoryOwn) {
    super(baseWRAPJNI.ProxyAudioProducer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProxyAudioProducer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        baseWRAPJNI.delete_ProxyAudioProducer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean setActualSndCardRecordParams(int nPtime, int nRate, int nChannels) {
    return baseWRAPJNI.ProxyAudioProducer_setActualSndCardRecordParams(swigCPtr, this, nPtime, nRate, nChannels);
  }

  public boolean setPushBuffer(java.nio.ByteBuffer pPushBufferPtr, long nPushBufferSize, boolean bUsePushCallback) {
    return baseWRAPJNI.ProxyAudioProducer_setPushBuffer__SWIG_0(swigCPtr, this, pPushBufferPtr, nPushBufferSize, bUsePushCallback);
  }

  public boolean setPushBuffer(java.nio.ByteBuffer pPushBufferPtr, long nPushBufferSize) {
    return baseWRAPJNI.ProxyAudioProducer_setPushBuffer__SWIG_1(swigCPtr, this, pPushBufferPtr, nPushBufferSize);
  }

  public int push(java.nio.ByteBuffer pBuffer, long nSize) {
    return baseWRAPJNI.ProxyAudioProducer_push__SWIG_0(swigCPtr, this, pBuffer, nSize);
  }

  public int push(java.nio.ByteBuffer pBuffer) {
    return baseWRAPJNI.ProxyAudioProducer_push__SWIG_1(swigCPtr, this, pBuffer);
  }

  public int push() {
    return baseWRAPJNI.ProxyAudioProducer_push__SWIG_2(swigCPtr, this);
  }

  public boolean setGain(long nGain) {
    return baseWRAPJNI.ProxyAudioProducer_setGain(swigCPtr, this, nGain);
  }

  public long getGain() {
    return baseWRAPJNI.ProxyAudioProducer_getGain(swigCPtr, this);
  }

  public void setCallback(ProxyAudioProducerCallback pCallback) {
    baseWRAPJNI.ProxyAudioProducer_setCallback(swigCPtr, this, ProxyAudioProducerCallback.getCPtr(pCallback), pCallback);
  }

  public java.math.BigInteger getMediaSessionId() {
    return baseWRAPJNI.ProxyAudioProducer_getMediaSessionId(swigCPtr, this);
  }

  public static boolean registerPlugin() {
    return baseWRAPJNI.ProxyAudioProducer_registerPlugin();
  }

}
