/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.imshello.baseWRAP;

public class ProxyVideoFrame {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ProxyVideoFrame(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProxyVideoFrame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        baseWRAPJNI.delete_ProxyVideoFrame(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long getSize() {
    return baseWRAPJNI.ProxyVideoFrame_getSize(swigCPtr, this);
  }

  public long getContent(java.nio.ByteBuffer pOutput, long nMaxsize) {
    return baseWRAPJNI.ProxyVideoFrame_getContent(swigCPtr, this, pOutput, nMaxsize);
  }

  public long getFrameWidth() {
    return baseWRAPJNI.ProxyVideoFrame_getFrameWidth(swigCPtr, this);
  }

  public long getFrameHeight() {
    return baseWRAPJNI.ProxyVideoFrame_getFrameHeight(swigCPtr, this);
  }

}
