/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.imshello.baseWRAP;

public class ProxyAudioConsumerCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ProxyAudioConsumerCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProxyAudioConsumerCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        baseWRAPJNI.delete_ProxyAudioConsumerCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    baseWRAPJNI.ProxyAudioConsumerCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    baseWRAPJNI.ProxyAudioConsumerCallback_change_ownership(this, swigCPtr, true);
  }

  public ProxyAudioConsumerCallback() {
    this(baseWRAPJNI.new_ProxyAudioConsumerCallback(), true);
    baseWRAPJNI.ProxyAudioConsumerCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public int prepare(int ptime, int rate, int channels) {
    return (getClass() == ProxyAudioConsumerCallback.class) ? baseWRAPJNI.ProxyAudioConsumerCallback_prepare(swigCPtr, this, ptime, rate, channels) : baseWRAPJNI.ProxyAudioConsumerCallback_prepareSwigExplicitProxyAudioConsumerCallback(swigCPtr, this, ptime, rate, channels);
  }

  public int start() {
    return (getClass() == ProxyAudioConsumerCallback.class) ? baseWRAPJNI.ProxyAudioConsumerCallback_start(swigCPtr, this) : baseWRAPJNI.ProxyAudioConsumerCallback_startSwigExplicitProxyAudioConsumerCallback(swigCPtr, this);
  }

  public int pause() {
    return (getClass() == ProxyAudioConsumerCallback.class) ? baseWRAPJNI.ProxyAudioConsumerCallback_pause(swigCPtr, this) : baseWRAPJNI.ProxyAudioConsumerCallback_pauseSwigExplicitProxyAudioConsumerCallback(swigCPtr, this);
  }

  public int stop() {
    return (getClass() == ProxyAudioConsumerCallback.class) ? baseWRAPJNI.ProxyAudioConsumerCallback_stop(swigCPtr, this) : baseWRAPJNI.ProxyAudioConsumerCallback_stopSwigExplicitProxyAudioConsumerCallback(swigCPtr, this);
  }

}
