/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.imshello.baseWRAP;

public class RPMessage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RPMessage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RPMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        baseWRAPJNI.delete_RPMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RPMessage() {
    this(baseWRAPJNI.new_RPMessage(), true);
  }

  public twrap_rpmessage_type_t getType() {
    return twrap_rpmessage_type_t.swigToEnum(baseWRAPJNI.RPMessage_getType(swigCPtr, this));
  }

  public long getPayloadLength() {
    return baseWRAPJNI.RPMessage_getPayloadLength(swigCPtr, this);
  }

  public long getPayload(java.nio.ByteBuffer output, long maxsize) {
    return baseWRAPJNI.RPMessage_getPayload(swigCPtr, this, output, maxsize);
  }

}
