/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.imshello.baseWRAP;

public class SdpMessage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SdpMessage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SdpMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        baseWRAPJNI.delete_SdpMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SdpMessage() {
    this(baseWRAPJNI.new_SdpMessage(), true);
  }

  public String getSdpHeaderValue(String media, char name, long index) {
    return baseWRAPJNI.SdpMessage_getSdpHeaderValue__SWIG_0(swigCPtr, this, media, name, index);
  }

  public String getSdpHeaderValue(String media, char name) {
    return baseWRAPJNI.SdpMessage_getSdpHeaderValue__SWIG_1(swigCPtr, this, media, name);
  }

  public String getSdpHeaderAValue(String media, String attributeName) {
    return baseWRAPJNI.SdpMessage_getSdpHeaderAValue(swigCPtr, this, media, attributeName);
  }

}
