/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.imshello.baseWRAP;

public class SipStack extends SafeObject {
  private long swigCPtr;

  protected SipStack(long cPtr, boolean cMemoryOwn) {
    super(baseWRAPJNI.SipStack_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SipStack obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        baseWRAPJNI.delete_SipStack(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SipStack(SipCallback pCallback, String realm_uri, String impi_uri, String impu_uri) {
    this(baseWRAPJNI.new_SipStack(SipCallback.getCPtr(pCallback), pCallback, realm_uri, impi_uri, impu_uri), true);
  }

  public boolean start() {
    return baseWRAPJNI.SipStack_start(swigCPtr, this);
  }

  public boolean setDebugCallback(DDebugCallback pCallback) {
    return baseWRAPJNI.SipStack_setDebugCallback(swigCPtr, this, DDebugCallback.getCPtr(pCallback), pCallback);
  }

  public boolean setDisplayName(String display_name) {
    return baseWRAPJNI.SipStack_setDisplayName(swigCPtr, this, display_name);
  }

  public boolean setRealm(String realm_uri) {
    return baseWRAPJNI.SipStack_setRealm(swigCPtr, this, realm_uri);
  }

  public boolean setIMPI(String impi) {
    return baseWRAPJNI.SipStack_setIMPI(swigCPtr, this, impi);
  }

  public boolean setIMPU(String impu_uri) {
    return baseWRAPJNI.SipStack_setIMPU(swigCPtr, this, impu_uri);
  }

  public boolean setPassword(String password) {
    return baseWRAPJNI.SipStack_setPassword(swigCPtr, this, password);
  }

  public boolean setAMF(String amf) {
    return baseWRAPJNI.SipStack_setAMF(swigCPtr, this, amf);
  }

  public boolean setOperatorId(String opid) {
    return baseWRAPJNI.SipStack_setOperatorId(swigCPtr, this, opid);
  }

  public boolean setProxyCSCF(String fqdn, int port, String transport, String ipversion) {
    return baseWRAPJNI.SipStack_setProxyCSCF(swigCPtr, this, fqdn, port, transport, ipversion);
  }

  public boolean setLocalIP(String ip, String transport) {
    return baseWRAPJNI.SipStack_setLocalIP__SWIG_0(swigCPtr, this, ip, transport);
  }

  public boolean setLocalIP(String ip) {
    return baseWRAPJNI.SipStack_setLocalIP__SWIG_1(swigCPtr, this, ip);
  }

  public boolean setLocalPort(int port, String transport) {
    return baseWRAPJNI.SipStack_setLocalPort__SWIG_0(swigCPtr, this, port, transport);
  }

  public boolean setLocalPort(int port) {
    return baseWRAPJNI.SipStack_setLocalPort__SWIG_1(swigCPtr, this, port);
  }

  public boolean setEarlyIMS(boolean enabled) {
    return baseWRAPJNI.SipStack_setEarlyIMS(swigCPtr, this, enabled);
  }

  public boolean addHeader(String name, String value) {
    return baseWRAPJNI.SipStack_addHeader(swigCPtr, this, name, value);
  }

  public boolean removeHeader(String name) {
    return baseWRAPJNI.SipStack_removeHeader(swigCPtr, this, name);
  }

  public boolean addDnsServer(String ip) {
    return baseWRAPJNI.SipStack_addDnsServer(swigCPtr, this, ip);
  }

  public boolean setDnsDiscovery(boolean enabled) {
    return baseWRAPJNI.SipStack_setDnsDiscovery(swigCPtr, this, enabled);
  }

  public boolean setAoR(String ip, int port) {
    return baseWRAPJNI.SipStack_setAoR(swigCPtr, this, ip, port);
  }

  public boolean setSigCompParams(long dms, long sms, long cpb, boolean enablePresDict) {
    return baseWRAPJNI.SipStack_setSigCompParams(swigCPtr, this, dms, sms, cpb, enablePresDict);
  }

  public boolean addSigCompCompartment(String compId) {
    return baseWRAPJNI.SipStack_addSigCompCompartment(swigCPtr, this, compId);
  }

  public boolean removeSigCompCompartment(String compId) {
    return baseWRAPJNI.SipStack_removeSigCompCompartment(swigCPtr, this, compId);
  }

  public boolean setSTUNEnabledForICE(boolean enabled) {
    return baseWRAPJNI.SipStack_setSTUNEnabledForICE(swigCPtr, this, enabled);
  }

  public boolean setSTUNServer(String ip, int port) {
    return baseWRAPJNI.SipStack_setSTUNServer(swigCPtr, this, ip, port);
  }

  public boolean setSTUNCred(String login, String password) {
    return baseWRAPJNI.SipStack_setSTUNCred(swigCPtr, this, login, password);
  }

  public boolean setSTUNEnabled(boolean enabled) {
    return baseWRAPJNI.SipStack_setSTUNEnabled(swigCPtr, this, enabled);
  }

  public boolean setTLSSecAgree(boolean enabled) {
    return baseWRAPJNI.SipStack_setTLSSecAgree(swigCPtr, this, enabled);
  }

  public boolean setSSLCertificates(String privKey, String pubKey, String caKey, boolean verify) {
    return baseWRAPJNI.SipStack_setSSLCertificates__SWIG_0(swigCPtr, this, privKey, pubKey, caKey, verify);
  }

  public boolean setSSLCertificates(String privKey, String pubKey, String caKey) {
    return baseWRAPJNI.SipStack_setSSLCertificates__SWIG_1(swigCPtr, this, privKey, pubKey, caKey);
  }

  public boolean setSSLCretificates(String privKey, String pubKey, String caKey, boolean verify) {
    return baseWRAPJNI.SipStack_setSSLCretificates__SWIG_0(swigCPtr, this, privKey, pubKey, caKey, verify);
  }

  public boolean setSSLCretificates(String privKey, String pubKey, String caKey) {
    return baseWRAPJNI.SipStack_setSSLCretificates__SWIG_1(swigCPtr, this, privKey, pubKey, caKey);
  }

  public boolean setIPSecSecAgree(boolean enabled) {
    return baseWRAPJNI.SipStack_setIPSecSecAgree(swigCPtr, this, enabled);
  }

  public boolean setIPSecParameters(String algo, String ealgo, String mode, String proto) {
    return baseWRAPJNI.SipStack_setIPSecParameters(swigCPtr, this, algo, ealgo, mode, proto);
  }

  public String dnsENUM(String service, String e164num, String domain) {
    return baseWRAPJNI.SipStack_dnsENUM(swigCPtr, this, service, e164num, domain);
  }

  public String dnsNaptrSrv(String domain, String service, int[] OUTPUT) {
    return baseWRAPJNI.SipStack_dnsNaptrSrv(swigCPtr, this, domain, service, OUTPUT);
  }

  public String dnsSrv(String service, int[] OUTPUT) {
    return baseWRAPJNI.SipStack_dnsSrv(swigCPtr, this, service, OUTPUT);
  }

  public boolean setMaxFDs(long max_fds) {
    return baseWRAPJNI.SipStack_setMaxFDs(swigCPtr, this, max_fds);
  }

  public String getLocalIPnPort(String protocol, int[] OUTPUT) {
    return baseWRAPJNI.SipStack_getLocalIPnPort(swigCPtr, this, protocol, OUTPUT);
  }

  public String getPreferredIdentity() {
    return baseWRAPJNI.SipStack_getPreferredIdentity(swigCPtr, this);
  }

  public boolean isValid() {
    return baseWRAPJNI.SipStack_isValid(swigCPtr, this);
  }

  public boolean stop() {
    return baseWRAPJNI.SipStack_stop(swigCPtr, this);
  }

  public static boolean initialize() {
    return baseWRAPJNI.SipStack_initialize();
  }

  public static boolean deInitialize() {
    return baseWRAPJNI.SipStack_deInitialize();
  }

  public static void setCodecs(tdav_codec_id_t codecs) {
    baseWRAPJNI.SipStack_setCodecs(codecs.swigValue());
  }

  public static void setCodecs_2(long codecs) {
    baseWRAPJNI.SipStack_setCodecs_2(codecs);
  }

  public static boolean setCodecPriority(tdav_codec_id_t codec_id, int priority) {
    return baseWRAPJNI.SipStack_setCodecPriority(codec_id.swigValue(), priority);
  }

  public static boolean setCodecPriority_2(int codec, int priority) {
    return baseWRAPJNI.SipStack_setCodecPriority_2(codec, priority);
  }

  public static boolean isCodecSupported(tdav_codec_id_t codec_id) {
    return baseWRAPJNI.SipStack_isCodecSupported(codec_id.swigValue());
  }

  public static boolean isIPSecSupported() {
    return baseWRAPJNI.SipStack_isIPSecSupported();
  }

}
