/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.imshello.baseWRAP;

public class SipUri {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SipUri(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SipUri obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        baseWRAPJNI.delete_SipUri(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SipUri(String uriString, String displayName) {
    this(baseWRAPJNI.new_SipUri__SWIG_0(uriString, displayName), true);
  }

  public SipUri(String uriString) {
    this(baseWRAPJNI.new_SipUri__SWIG_1(uriString), true);
  }

  public static boolean isValid(String arg0) {
    return baseWRAPJNI.SipUri_isValid__SWIG_0(arg0);
  }

  public boolean isValid() {
    return baseWRAPJNI.SipUri_isValid__SWIG_1(swigCPtr, this);
  }

  public String getScheme() {
    return baseWRAPJNI.SipUri_getScheme(swigCPtr, this);
  }

  public String getHost() {
    return baseWRAPJNI.SipUri_getHost(swigCPtr, this);
  }

  public int getPort() {
    return baseWRAPJNI.SipUri_getPort(swigCPtr, this);
  }

  public String getUserName() {
    return baseWRAPJNI.SipUri_getUserName(swigCPtr, this);
  }

  public String getPassword() {
    return baseWRAPJNI.SipUri_getPassword(swigCPtr, this);
  }

  public String getDisplayName() {
    return baseWRAPJNI.SipUri_getDisplayName(swigCPtr, this);
  }

  public String getParamValue(String pname) {
    return baseWRAPJNI.SipUri_getParamValue(swigCPtr, this, pname);
  }

  public void setDisplayName(String displayName) {
    baseWRAPJNI.SipUri_setDisplayName(swigCPtr, this, displayName);
  }

}
