/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.imshello.baseWRAP;

public class SubscriptionSession extends SipSession {
  private long swigCPtr;

  protected SubscriptionSession(long cPtr, boolean cMemoryOwn) {
    super(baseWRAPJNI.SubscriptionSession_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SubscriptionSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        baseWRAPJNI.delete_SubscriptionSession(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SubscriptionSession(SipStack pStack) {
    this(baseWRAPJNI.new_SubscriptionSession(SipStack.getCPtr(pStack), pStack), true);
  }

  public boolean subscribe() {
    return baseWRAPJNI.SubscriptionSession_subscribe(swigCPtr, this);
  }

  public boolean unSubscribe() {
    return baseWRAPJNI.SubscriptionSession_unSubscribe(swigCPtr, this);
  }

}
