/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_imshello_droid_Utils_USBCamera */

#ifndef _Included_org_imshello_droid_Utils_USBCamera
#define _Included_org_imshello_droid_Utils_USBCamera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_imshello_droid_Utils_USBCamera
 * Method:    SetDevName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_imshello_droid_Utils_USBCamera_SetDevName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_imshello_droid_Utils_USBCamera
 * Method:    SetCaptureParameters
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_imshello_droid_Utils_USBCamera_SetCaptureParameters
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_imshello_droid_Utils_USBCamera
 * Method:    StartCapture
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_imshello_droid_Utils_USBCamera_StartCapture
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_imshello_droid_Utils_USBCamera
 * Method:    StopCapture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_imshello_droid_Utils_USBCamera_StopCapture
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
